# Generated by Django 5.2.5 on 2025-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_product_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_photo",
            field=models.URLField(),
        ),
    ]
