# Generated by Django 5.2.5 on 2025-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_alter_product_product_photo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_price"], name="ecommerce_p_product_c947cc_idx"
            ),
        ),
    ]
