# Generated by Django 5.2.5 on 2025-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_alter_order_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_photo",
            field=models.URLField(),
        ),
    ]
