# Generated by Django 5.2.5 on 2025-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0008_alter_product_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_photo",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
