"""
Django settings for sujal project.
Generated by 'django-admin startproject' using Django 5.1.6.
"""

from pathlib import Path
import os

# Logging for SQL queries (optional)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {  
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {  
            'handlers': ['console'],
            'level': 'DEBUG',     
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mv%cbg-x6$mv5^3psthjccv9h+hwpbcu2(aw0p40mj2d-g^ezd"

# Stripe Keys
STRIPE_SECRET_KEY = "sk_test_51ReqJkPxW6S68voWUDqpzYJpep6AQRw55vtMhDvrxJjOw5MftRtsaOoAPGZ10fnPfibdk6Y85aWvinhn9s841itu00Es023Hi3"
STRIPE_PUBLISHABLE_KEY = "pk_test_51ReqJkPxW6S68voWQuy8STC32Nti2gwd4eki2KxQw0sY1YTA49UnmXF6IRi42CzWTsGY7t9vq1LYK3m5Hw1LrEZx00CB4LAJVn"

DEBUG = False
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'ecommerce',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'

# Database - Supabase PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Sujalsingal@12',
        'HOST': 'db.bvscsqvzxxvssuqciiry.supabase.co',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',  # required for Supabase
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
